Python Programs/Bubble_Sort.py

Added Bubble sort algorithm by using Python

Added Bubble sort algorithm by using Python

---

Cpp_Program/Search_Insertion_Pos.cpp

added my cod for binary search

add binary search problem

---

C++ Programs/prism_algo.cpp

pls add the tag of hacktoberfest and hacktoberfest-accepted

prism's algo in cpp

---

C++ Programs/bubble_sort.cpp

Here is realization of bubble sort using templated function

Added bubble sort for C++

---

Python Programs/gradient_descent.py

`gradient_descent.py` calculates the gradient of a function `x^2`. You can replace the `objective` function to calculate the derivative of other functions.

added gradient descent

---

Python Programs/def_integrals.py

`def_integrals.py` calculates the Definite integral. In this script, we're calculating the definite integral of `x^2`. You can change the return value of `f(x)` for other functions.

added definite integrals calculator

---

JavaScript Programs/Palindrome_Checker.js

feat : JS Palindrome

---

C++ Programs/Moore's Voting Algorithms.cpp

Please add my algorithm file to your repository with hacktoberfest

Moore's Voting Algorithm

---

C++ Programs/K Closest Points to Origin.cpp

Given an array of points where points[i] = [xi, yi] represents a point on the X-Y plane and an integer k, return the k closest points to the origin (0, 0).
The distance between two points on the X-Y plane is the Euclidean distance (i.e., √(x1 - x2)^2 + (y1 - y2)^2). You may return the answer in any order. The answer is guaranteed to be unique (except for the order that it is in).
Input: points = [[3,3],[5,-1],[-2,4]], k = 2
Output: [[3,3],[-2,4]]
Explanation: The answer [[-2,4],[3,3]] would also be accepted.
Constraints:
1 <= k <= points.length <= 10^4
-10^4 < xi, yi < 10^4

CPP code of K Closest Points to Origin (using heap)

---

C++ Programs/binary_search.cpp

added binary_search.cpp

---

C++ Programs/Kadane's Algorithms.cpp

Please add my file to your repository with label hacktoberfest2022

Kadane's Algorithms

---

C++ Programs/boundarytraversal_bt.cpp

Added Boundary traversal of binary tree

Boundary traversal of binary tree

---

C++ Programs/quickSort.cpp

This pull request has added Quick Sort.

Added Quick Sort

---

Python Programs/Knapsack.py

I added a python implementation of the knapsack algorithm using dynamic programming and a function to test it. Please review and let me know what you think.

Add knapsack algorithm and test function

---

C++ Programs/fibonacci_series.cpp

The Fibonacci sequence is a series where the next term is the sum of the previous two terms. The first two terms of the Fibonacci sequence are 0 followed by 1.

added C++ for Fibonacci Series

---

Python Programs/AVL Tree(Balanced Binary Search Tree).py
Python Programs/Bellman Ford algorithm.py
Python Programs/Binary Search Tree.py
Python Programs/Breadth First Search.py
Python Programs/Depth First Search.py
Python Programs/Dijkstra's Shortest Path algorithm.py
Python Programs/Heap_Python Buitlt in function.py
Python Programs/Linked Lists.py
Python Programs/Merge Sort.py
Python Programs/Prims-Jarnik Algorithm MST.py
Python Programs/Queue.py
Python Programs/Quick sort.py
Python Programs/Selection sort.py
Python Programs/Stack.py

I am contributing these files for Hacktoberfest.

Added python program files related to DSA (Hacktoberfest)

---

C++ Programs/LongestPalindrome.cpp
C++ Programs/buySellStocks.cpp

Provide an approving review of a PR/MR
Add the “hacktoberfest-accepted” label

my commit 1 for hactoberfest

---

C++ Programs/JobSequencing.cpp

Added Job Sequencing Algorithm

Added Job Sequencing Algorithm

---

C++ Programs/code for finding the SQUARE ROOT  of any no.cpp

pls accept my pull request and give a tag of hactoberfest. thank you

Create code for finding the SQUARE ROOT  of any no.cpp

---

C++ Programs/Random_quickSort.cpp
C++ Programs/bucket_sort.cpp
C++ Programs/random_select.cpp

Randomized Select

---

C++ Programs/FractionalKnapsack.cpp

Added Fractional Knapsack Problem

Added Fractional Knapsack Problem

---

C++ Programs/CoinChange.cpp

Added Coin Change Problem

---

C++ Programs/FriendsPairing.cpp

Added Friends Pairing Problem

---

C++ Programs/0-1Knapsack.cpp

Added 0-1 Knapsack Problem

---

C Programs/swap_number.c

This program swapped two numbers without a third variable.

added swap number

---

C# Programs/merge sort.cs

The Merge Sort algorithm is a sorting algorithm that is based on the Divide and Conquer paradigm. In this algorithm, the array is initially divided into two equal halves and then they are combined in a sorted manner.

Created merge sort.cs

---

C++ Programs/Stock Span.cpp

The stock span problem is a financial problem where we have a series of n daily price quotes for a stock and the task is to calculate the span of stocks price for all n days.
[Practice Link - GFG](https://practice.geeksforgeeks.org/problems/stock-span-problem-1587115621/0)

Stock Span Problem

---

C++ Programs/DestinationCity.cpp

[LeetCode 1436](https://leetcode.com/problems/destination-city/)
The task is to make the adjacency matrix, for that we map each city name to a number for easy iteration, then check in adjacency matrix which vertex's size is zero and print the corresponding key from the map.

estinationCity.cpp

---

C Programs/Binary Search.c

Binary Search is a searching algorithm used in a sorted array by repeatedly dividing the search interval in half. The idea of binary search is to use the information that the array is sorted and reduce the time complexity to O(Log n).
Hey i have contributed by making binary search algorithms in c language kindly accept my pull request and give me the lable of hacktoberfest

Created Binary Search.c

---

C Programs/Selection_Sort.c

selection sort in c

---

C Programs/Bubble_Sort.c
C Programs/Selection_Sort.c

Bubble sort

---

Python Programs/longestValidParentheses.py

Given a string containing just the characters '(' and ')', find the length of the longest valid (well-formed) parentheses substring.

longestValidParentheses.py

---

C++ Programs/Dynamic programming/Delete-operation-for-two-strings.cpp
C++ Programs/image_overlap_leetcode.cpp

Problem statement
input output statement
code

image_overlap leetcode challenge
